{% set name = 'clingoDL' %}
{% set dev = not environ.get('BUILD_RELEASE', false) %}
{% set version = environ.get('VERSION_NUMBER', "1.0.0") %}
{% set build = environ.get('BUILD_NUMBER', "0") %}

package:
  name: clingo-dl
  version: {{ version }}

source:
{% if dev %}
  git_rev: wip
  git_url: https://github.com/potassco/{{ name }}.git
{% else %}
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.tar.gz
{% endif %}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - clingo
  run:
    - {{ pin_compatible('python') }}
    - {{ pin_compatible('clingo') }}

build:
  number: {{ build }}
  skip: True [win and vc<14]

test:
  commands:
    - clingo-dl --version

about:
  home:  https://potassco.org/
  license: MIT
  summary: A solver for logic programs with difference constraints.
  description: The clingo-dl solver extends the clingo ASP system with support for difference logic constraints.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}
